name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clib
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-gnutls-dev valgrind -qq
          git clone https://github.com/clibs/clib.git /tmp/clib
          sudo make -C /tmp/clib install
      - name: Install dependencies
        run: clib install
      - name: Run tests
        run: make test
      - run: valgrind --leak-check=full --error-exitcode=5 ./test
